/*
 * eDIP_TFT_flash.h
 *
 * Created: 21.03.2013 15:14:37
 *  Author: JochenAlt
 */ 


#ifndef EDIP_TFT_FLASH_H_
#define EDIP_TFT_FLASH_H_


#define LCD_WIDTH 320
#define LCD_HEIGHT 240

// these are the numbers that refer to the displays EEPROM

// font sizes in use
#define FONT4x6   1
#define FONT6x8   2
#define GENEVA10  3
#define GENEVA12  4
#define GENEVA13  5
#define GENEVA15  6
#define SEGOE15   7
#define SEGOE18   8
#define SEGOE20   9
#define SEGOE22   10
#define SEGOE24   11
#define SEGOE36   12
#define SEGOE48   13

// Splash Screen Bitmaps
#define FONT_TINY FONT4x6  
#define FONT_SMALL GENEVA13
#define FONT_DEFAULT GENEVA15 
#define FONT_LARGE SEGOE18
#define FONT_GRANT SEGOE20
#define FONT_HUGE SEGOE36
#define FONT_GIANT SEGOE48 

#define FONT_TINY_HEIGHT 6  
#define FONT_SMALL_HEIGHT 13
#define FONT_DEFAULT_HEIGHT 15 
#define FONT_LARGE_HEIGHT 18
#define FONT_GRANT_HEIGHT 20
#define FONT_HUGE_HEIGHT 36
#define FONT_GIANT_HEIGHT 48 

#define FONT_TINY_WIDTH(x)    ((x==0)?4:4)		// 4-4 monospaced
#define FONT_SMALL_WIDTH(x)   ((x==0)?3:11)		// 3-11
#define FONT_DEFAULT_WIDTH(x) ((x==0)?3:12)		// 3-12
#define FONT_LARGE_WIDTH(x)   ((x==0)?3:12)		// 3-12
#define FONT_GRANT_WIDTH(x)   ((x==0)?3:16)		// 3-16
#define FONT_HUGE_WIDTH(x)    ((x==0)?8:33)		// 8-34
#define FONT_GIANT_WIDTH(x)   ((x==0)?10:43)	// 10-44

// colors 
#define BLACK_NO 1
#define WHITE_NO 8
#define DARK_GREY 9

#define TRANSPARENT_COLOR 0
#define ACCENT_COLOR1_NO 17
#define ACCENT_COLOR2_NO 18
#define PASSIVE_TEXT_COLOR_NO 9
#define ACTIVE_TEXT_COLOR_NO WHITE_NO
#define BACKGROUND_COLOR_NO BLACK_NO
#define MAINVIEW_PAUL_LINE_COLOR 19

// Splash View
#define SPLASH_VIEW_PG 0
#define PAUL_BITMAP_NO 1
#define PAUL_RIGHT_TILT_BITMAP_NO 2
#define PAUL_LEFT_TILT_BITMAP_NO 3
#define PAUL_HALF_LEFT_TILT_BITMAP_NO 4
#define PAUL_HALF_RIGHT_TILT_BITMAP_NO 5

#define PAULS_EYES_BITMAP_NO 4
#define PAULS_EYES_EXITED_BITMAP_NO 5
#define PAULS_EYES_FULL_BLINK_BITMAP_NO 6
#define PAULS_EYES_HALF_BLINK_BITMAP_NO 7
#define PAULS_EYES_LEFT_EYES_BITMAP_NO 8
#define PAULS_EYES_RIGHT_EYES_BITMAP_NO 9
#define PAULS_EYES_BUT_SAD_BITMAP_NO 10

// main View 
#define MAINVIEW_PAUL_BACKGROUND_BITMAP_NO 11
#define MAINVIEW_PAUL_HEAD_BITMAP_NO 12


// themes
#define THEME_FIRST_COLOR_NO 20
#define THEME_SECOND_COLOR_NO 21

// orange
#define THEME1_FIRST_RGB_COLOR 228,108,10
#define THEME1_SECOND_RGB_COLOR 250,192,144
#define THEME1_MAINVIEW_LINE_RGB_COLOR 172,82,8
#define THEME1_LCD_PAGE 1

// green
#define THEME2_FIRST_RGB_COLOR 119,147,60
#define THEME2_SECOND_RGB_COLOR 195,214,155
#define THEME2_MAINVIEW_LINE_RGB_COLOR 79,89,40
#define THEME2_LCD_PAGE 2

// mint
#define THEME3_FIRST_RGB_COLOR 0,188,184
#define THEME3_SECOND_RGB_COLOR 167,255,253
#define THEME3_MAINVIEW_LINE_RGB_COLOR 0,102,102
#define THEME3_LCD_PAGE 3

// beige
#define THEME4_FIRST_RGB_COLOR 196,189,151
#define THEME4_SECOND_RGB_COLOR 221,217,195
#define THEME4_MAINVIEW_LINE_RGB_COLOR 74,69,42
#define THEME4_LCD_PAGE 4

// turquoise
#define THEME5_FIRST_RGB_COLOR 147,205,221
#define THEME5_SECOND_RGB_COLOR 183,222,232
#define THEME5_MAINVIEW_LINE_RGB_COLOR 33,89,104
#define THEME5_LCD_PAGE 5

// dark blue
#define THEME6_FIRST_RGB_COLOR 149,179,215
#define THEME6_SECOND_RGB_COLOR 220,230,242
#define THEME6_MAINVIEW_LINE_RGB_COLOR 37,64,97
#define THEME6_LCD_PAGE 6

// Arrows
#define ARROW_DOWN_BITMAP_NO 13
#define ARROW_UP_BITMAP_NO 14
#define ARROW_RIGHT_BITMAP_NO 15
#define ARROW_LEFT_BITMAP_NO 16

// Symbols
#define LOUDSPEAKER_BITMAP_NO 17
#define TALKING_SPEED_BITMAP_NO 18
#define BRIGHTNESS_BITMAP_NO 19

// main View
#define MAINVIEW_BITMAP_PG 0

#endif /* EDIP-TFT-FLASH_H_ */